# Generated by Django 4.0.1 on 2022-02-08 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_following_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peron_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
