# Generated by Django 4.0.1 on 2022-02-18 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_likes_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
    ]
